name: Upload Python Package

on:
  push:
  pull_request:
  schedule:
    - cron: "* * * * 4"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Test asynchronous function
      run: python asynctest.py
    - name: Test OTR function
      run: python otrtest.py
    - name: Test main functions
      run: python maintest.py