name: Test with Python 3.7

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * 4"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: python -m pip install -r testrequirements.txt
    - name: Test asynchronous function
      run: python asynctest.py
    - name: Test OTR function
      run: python otrtest.py
    - name: Test main functions
      run: python maintest.py
